---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-perl-ex
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/therealshabi/hello-world-1
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: perl-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/s2i-perl
