---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-java-pr-ex
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/spring-projects/spring-petclinic
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-java-openjdk-11-ubi8-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/s2i-java-openjdk-11-ubi8
