apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: maven-pipeline
spec:
  workspaces:
  - name: source
  - name: maven-settings
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/che-samples/console-java-simple
    - name: deleteExisting
      value: "true"
  - name: build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - clone-git-repo
    workspaces:
    - name: source
      workspace: source
    - name: maven-settings
      workspace: maven-settings
      params:
    - name: MAVEN_IMAGE
      value: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
