apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-python-pipeline
spec:
  params:
  - name: VERSION
    description: version of Python
  - name: SUBDIR
    description: where to clone the git repo
    default: s2i-python
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/sclorg/django-ex
    - name: subdirectory
      value: $(params.SUBDIR)
    - name: deleteExisting
      value: "true"
  - name: build
    taskRef:
      name: s2i-python
      kind: ClusterTask
    runAfter: 
    - clone-git-repo
    workspaces:
    - name: source
      workspace: source
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/s2i-python-$(params.VERSION)
    - name: VERSION
      value: $(params.VERSION)
    - name: PATH_CONTEXT
      value: $(params.SUBDIR)
    - name: TLSVERIFY
      value: "false"
