apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: buildah-pipeline
spec:
  params:
  - name: IMAGE
    description: where to push result of buildah build
  - name: SUBDIR
    description: where to clone the git repo
    default: buildah
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/kelseyhightower/nocode
    - name: subdirectory
      value: $(params.SUBDIR)
    - name: deleteExisting
      value: "true"
  - name: run-buildah
    taskRef:
      name: buildah
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: source
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: CONTEXT
      value: $(params.SUBDIR)
    - name: TLSVERIFY
      value: "false"