---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nocode
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/kelseyhightower/nocode
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: buildah-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/nocode