apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-java-pipeline
spec:
  params:
  - name: VERSION
    description: The tag of 'java' imagestream for Java version
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/spring-projects/spring-petclinic
    - name: subdirectory
      value: s2i-java-$(params.VERSION)
    - name: deleteExisting
      value: "true"
    - name: revision
      value: main
  - name: build
    taskRef:
      name: s2i-java
      kind: ClusterTask
    runAfter: 
    - clone-git-repo
    workspaces:
    - name: source
      workspace: source
    params:
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/s2i-java-$(params.VERSION)
    - name: PATH_CONTEXT
      value: s2i-java-$(params.VERSION)
    - name: TLSVERIFY
      value: "false"
    - name: VERSION
      value: $(params.VERSION)
