apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-go-pipeline
spec:
  params:
  - name: SUBDIR
    description: where to clone the git repo
    default: s2i-go
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/che-samples/console-java-simple
    # - name: subdirectory
    #   value: $(params.SUBDIR)
    - name: deleteExisting
      value: "true"
  - name: build
    taskRef:
      name: s2i-go
      kind: ClusterTask
    runAfter: 
    - clone-git-repo
    workspaces:
    - name: source
      workspace: source
    params:
    # - name: PATH_CONTEXT
    #   value: $(params.SUBDIR)
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/s2i-go
    - name: TLSVERIFY
      value: "false"
