apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: s2i-pipeline
spec:
  params:
  - name: BUILDER_IMAGE
    description: The location of the s2i builder image
  - name: GIT_REPO
    description: URL of Git repository to clone
  - name: PATH_CONTEXT
    description: The location of the path to run s2i from
    default: '.'
  - name: SUBDIR
    description: Where to clone the git repo
    default: s2i
  resources:
    - name: image
      type: image
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: subdirectory
      value: $(params.SUBDIR)
    - name: deleteExisting
      value: "true"
  - name: build
    taskRef:
      name: s2i
      kind: ClusterTask
    workspaces:
    - name: source
      workspace: source
    params:
    - name: BUILDER_IMAGE
      value: $(params.BUILDER_IMAGE)
    - name: PATH_CONTEXT
      value: $(params.SUBDIR)/$(params.PATH_CONTEXT)
    - name: TLSVERIFY
      value: "false"
    resources:
      outputs:
      - name: image
        resource: image
