---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-python-3-ex
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/sclorg/django-ex
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: python-3-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/s2i-python-3
