---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-php-ex
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/sclorg/s2i-php-container/
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-php-73-ubi8-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/s2i-php-73-ubi8-pr
