---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: s2i-java-11-ex
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/spring-projects/spring-petclinic
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: java-11-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/s2i-java-11
