apiVersion: v1
kind: ServiceAccount
metadata:
  name: kn-deployer-account
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kn-deployer
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "revisions", "routes"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kn-deployer-binding
subjects:
- kind: ServiceAccount
  name: kn-deployer-account
  # namespace: default
roleRef:
  kind: Role
  name: kn-deployer
  apiGroup: rbac.authorization.k8s.io
