apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jib-maven-pipeline
spec:
  params:
  - name: SUBDIR
    description: where to clone the git repo
    default: jib-maven
  workspaces:
  - name: source
  tasks:
  - name: clone-git-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: source
    params:
    - name: url
      value: https://github.com/che-samples/console-java-simple
    - name: subdirectory
      value: $(params.SUBDIR)
    - name: deleteExisting
      value: "true"
  - name: build
    taskRef:
      name: jib-maven
      kind: ClusterTask
    runAfter:
    - clone-git-repo
    workspaces:
    - name: source
      workspace: source
    params:
    - name: DIRECTORY
      value: $(params.SUBDIR)
    - name: IMAGE
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/console-java-simple
    - name: INSECUREREGISTRY
      value: "true"
