---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jib-maven-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jib-maven-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/console-java-simple
