apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jib-maven-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/catalog-tests/console-java-simple
