---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: console-java-simple
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/che-samples/console-java-simple
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: jib-maven-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/tekton-catalog/console-java-simple